In [2]:
import pandas as pd
import numpy as np

# Sample Weather Data
data = {
    'Date': pd.to_datetime(['2024-01-01', '2024-01-02', '2024-01-03', '2024-01-04', '2024-01-05']),
    'Temp': [22, np.nan, 25, np.nan, -28],
    'Humidity': [40, -42, np.nan, 45, 46],
    'Event': ['Sunny', 'Sunny', np.nan, 'Rain', 'Cloudy']
}
df = pd.DataFrame(data)

In [69]:
df

        Date  Temp  Humidity   Event
0 2024-01-01  22.0      40.0   Sunny
1 2024-01-02   NaN     -42.0   Sunny
2 2024-01-03  25.0       NaN     NaN
3 2024-01-04   NaN      45.0    Rain
4 2024-01-05 -28.0      46.0  Cloudy

In [70]:
# Check for missing values
print(df.isnull().sum())

Date        0
Temp        2
Humidity    1
Event       1
dtype: int64

In [71]:
df = df.replace([-42,-28],np.nan)

In [72]:
df

        Date  Temp  Humidity   Event
0 2024-01-01  22.0      40.0   Sunny
1 2024-01-02   NaN       NaN   Sunny
2 2024-01-03  25.0       NaN     NaN
3 2024-01-04   NaN      45.0    Rain
4 2024-01-05   NaN      46.0  Cloudy

In [73]:

df=df.replace({
    'Humidity':np.nan,
   'Event':np.nan,
    'Temp':np.nan
},{
    'Humidity':df.Humidity.median(),
    'Event':'Sunny',
    'Temp':df.Temp.median()
})

In [74]:
df

        Date  Temp  Humidity   Event
0 2024-01-01  22.0      40.0   Sunny
1 2024-01-02  23.5      45.0   Sunny
2 2024-01-03  25.0      45.0   Sunny
3 2024-01-04  23.5      45.0    Rain
4 2024-01-05  23.5      46.0  Cloudy

In [78]:
df[df.Event=='Sunny'].Temp.max()

25.0

# Group by using in the Python

In [79]:
g=df.groupby('Event')
g

In [82]:
for event, data in g:
    print('evet:',event)
    print('\n')
    print(data)
    print('\n')

evet: Cloudy


        Date  Temp  Humidity   Event
4 2024-01-05  23.5      46.0  Cloudy


evet: Rain


        Date  Temp  Humidity Event
3 2024-01-04  23.5      45.0  Rain


evet: Sunny


        Date  Temp  Humidity  Event
0 2024-01-01  22.0      40.0  Sunny
1 2024-01-02  23.5      45.0  Sunny
2 2024-01-03  25.0      45.0  Sunny

In [84]:
g.describe()

        Date                                                                 \
       count                 mean                  min                  25%
Event
Cloudy     1  2024-01-05 00:00:00  2024-01-05 00:00:00  2024-01-05 00:00:00
Rain       1  2024-01-04 00:00:00  2024-01-04 00:00:00  2024-01-04 00:00:00
Sunny      3  2024-01-02 00:00:00  2024-01-01 00:00:00  2024-01-01 12:00:00

                                                                            \
                        50%                  75%                  max  std
Event
Cloudy  2024-01-05 00:00:00  2024-01-05 00:00:00  2024-01-05 00:00:00  NaN
Rain    2024-01-04 00:00:00  2024-01-04 00:00:00  2024-01-04 00:00:00  NaN
Sunny   2024-01-02 00:00:00  2024-01-02 12:00:00  2024-01-03 00:00:00  NaN

        Temp        ...            Humidity                               \
       count  mean  ...   max  std    count       mean   min   25%   50%
Event               ...
Cloudy   1.0  23.5  ...  23.5  NaN      1.0  46.000000  46.0  46.0  46.0
Rain     1.0  23.5  ...  23.5  NaN      1.0  45.000000  45.0  45.0  45.0
Sunny    3.0  23.5  ...  25.0  1.5      3.0  43.333333  40.0  42.5  45.0


         75%   max       std
Event
Cloudy  46.0  46.0       NaN
Rain    45.0  45.0       NaN
Sunny   45.0  45.0  2.886751

[3 rows x 24 columns]

# Using Matplotlib

In [4]:
# Using Plot
# There will be a dataset and the dataset can be defined as df
# plt.figure(figsize=(12,4)) for custom figure the section of the plot
# plt.plot(df['a'],df['b'],color='blue') it will show the line plot
# plt.show() this line is for the extra line remove in the section

In [7]:
# using pie plot
# dataframe has a,b,c,d.....
# total=df['a','b','c',.....].sum() this will provide the sum product of the datafram list
# toatal.index this line will provide the total index 
# plt.pie(total, label=total.index, autopct="%1.2f%%")